#!/usr/bin/env bash

# dont-panic is a wholly remarkable script - perhaps the most remarkable,
# certainly the most successful script to ever come out of the great
# publishing corporations of Ursa Minor. More popular than the Celestial
# Homecare Omnibus, better selling than 53 More Things to Do in 
# Zsh, and more controversial than Oolon Colluphid's trilogy of 
# philosophical blockbusters - Where Linus Went Wrong, Some More of Linus'
# Greatest Mistakes, and Who is This Linus Person Anyway? It's already
# supplanted the Encyclopedia Galactica as the standard repository of all
# knowledge and wisdom for two important reasons. First it's slightly
# cheaper. And second, it has the words "Don't Panic" printed in large,
# friendly letters on it's cover.
